/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Text-Convert.h
 #	source generated by 4D Plugin Wizard
 #	Project : Text Convert
 #	author : miyako
 #	2021/06/29
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_TEXT_CONVERT_H
#define PLUGIN_TEXT_CONVERT_H

#include "4DPluginAPI.h"
#include "ARRAY_TEXT.h"
#include "ARRAY_LONGINT.h"
#include "C_TEXT.h"
#include "C_BLOB.h"
#include "C_LONGINT.h"

#pragma mark -

static void ICU_GET_ENCODING_LIST(PA_PluginParameters params);
static void ICU_Get_good_encodings(PA_PluginParameters params);
static void ICU_Get_best_encoding(PA_PluginParameters params);
static void ICU_Normalize_text(PA_PluginParameters params);
static void ICU_Transform_text(PA_PluginParameters params);
static void ICU_Get_error_text(PA_PluginParameters params);
static void ICU_Convert_to_text(PA_PluginParameters params);
static void ICU_Convert_from_text(PA_PluginParameters params);
static void ICONV_Convert(PA_PluginParameters params);
static void JIS_Convert_to_text(PA_PluginParameters params);
static void JIS_Convert_from_text(PA_PluginParameters params);
static void ICONV_GET_ENCODING_LIST(PA_PluginParameters params);
static void CP_GET_ENCODING_LIST(PA_PluginParameters params);
static void CP_Get_best_encoding(PA_PluginParameters params);
static void CP_Convert_from_text(PA_PluginParameters params);
static void CP_Convert_to_text(PA_PluginParameters params);
static void CP_Get_good_encodings(PA_PluginParameters params);

#if VERSIONMAC
#include "cpmap.h"
#include <iconv.h>
#endif

#if VERSIONWIN
#include <mlang.h>
#include "iconv.h"
#endif

#define ERR_INVALID_ENCODING (-1)
#define ERR_CONVERSION_FAILED (-2)
#define ERR_DETECTION_FAILED (-3)

#define JIS7_SO_SI 0
#define JIS7_ESC 1
#define JIS8 2

typedef enum
{
    kG0Undefined    = 0,
    kG0ASCII        = 1,
    kG0JIS            = 2
}eG0Mode;

#define MAX_LENGTH_FOR_ENCODING_NAME (255)

#include "unicode/ucnv.h"
#include "unicode/utrans.h"
#include "unicode/ucsdet.h"
#include "unicode/unorm2.h"

typedef enum
{
    _NFC = 0,
    _NFD = 1,
    _NFKC = 2,
    _NFKD = 3,
    _NFKC_CF = 4
} NormalizationForm;

#endif /* PLUGIN_TEXT_CONVERT_H */
